//! S-owned run attachments. Persistence never supplies P admission or planner/physical proof.
mod files;
mod run_store;

use crate::journal::{Basis, Journal, Scope};
use rx_domain::{canonical, types::*};
use rx_ports::{Document, Record, Repository, Result, StoreError, Transaction};
use rx_process_contract::{execution::RunState, production};
use serde::{Deserialize, Serialize, de::DeserializeOwned};
use std::collections::BTreeSet;

pub use files::RecoveredFile;
pub use run_store::RunStore;
const HEADER: &str = "rx.executor-attachment-header.v2";
const STATE: &str = "rx.executor-attachment-state.v1";
const RECORD: &str = "rx.executor-attachment.v1";
const INDEX: &str = "rx.executor-attachment-index.v1";
const PREFIX: &str = "attachment/run/";
const CREATION: &str = "rx.executor-run-creation-entered.v1";
const CREATION_PREFIX: &str = "attachment/creation-entered/";
const MAX_ATTACHMENTS: usize = 1024;

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ServiceScope {
    pub installation: Id,
    pub store_generation: Id,
    pub principal: Name,
    pub release: Digest,
    pub cell: Name,
    pub definition: Digest,
}
impl ServiceScope {
    fn matches(&self, run: &Scope) -> bool {
        self.installation == run.installation
            && self.store_generation == run.store_generation
            && self.principal == run.principal
            && self.release == run.release
            && self.cell == run.cell
            && self.definition == run.definition
    }
}

/// Supplied by installation metadata, never regenerated by required-open.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Identity {
    pub journal: Id,
    pub scope: ServiceScope,
}

/// The caller must obtain this context from the authenticated P read before preparing it.
/// The journal records its original bytes; it does not validate network authority or freshness.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Preparation {
    pub id: Id,
    pub run_journal: Id,
    pub scope: Scope,
    pub executor_session: Id,
    pub epoch: Counter,
    pub basis: Basis,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Phase {
    Preparing,
    Attached,
    Closed,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Attachment {
    pub preparation: Preparation,
    pub phase: Phase,
    pub completion: Option<Box<production::View>>,
}
#[derive(Clone, Debug)]
pub struct VersionedAttachment {
    pub revision: Counter,
    pub value: Attachment,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct State {
    current: Option<Id>,
    count: Counter,
}

pub struct AssignmentJournal<R> {
    repository: R,
    identity: Identity,
}

impl<R: Repository> AssignmentJournal<R> {
    /// Explicit initialization only. On a lost commit response, recover using open_required.
    pub fn initialize(mut repository: R, identity: Identity) -> Result<Self> {
        let (head, records) = repository.snapshot()?;
        if head.0 != 0 || !records.is_empty() {
            return invalid("attachment initialization requires an empty store/history");
        }
        repository.transact(|tx| {
            if tx.get(&name("attachment/header"))?.is_some() || tx.control_head()?.0 != 0 {
                return invalid("attachment initialization requires an empty store");
            }
            tx.put(&name("attachment/header"), None, &doc(HEADER, &identity)?)?;
            tx.put(
                &name("attachment/state"),
                None,
                &doc(
                    STATE,
                    &State {
                        current: None,
                        count: Counter(0),
                    },
                )?,
            )?;
            Ok(())
        })?;
        Ok(Self {
            repository,
            identity,
        })
    }

    /// Missing metadata, changed identities and incomplete indices are failures, never init.
    pub fn open_required(mut repository: R, identity: Identity) -> Result<Self> {
        repository.transact(|tx| audit(tx, &identity).map(|_| ()))?;
        Ok(Self {
            repository,
            identity,
        })
    }
    pub fn identity(&self) -> &Identity {
        &self.identity
    }
    pub fn into_repository(self) -> R {
        self.repository
    }
    pub fn current(&mut self) -> Result<Option<VersionedAttachment>> {
        self.repository.transact(|tx| {
            let state = audit(tx, &self.identity)?;
            state.current.as_ref().map(|id| read(tx, id)).transpose()
        })
    }
    pub fn get(&mut self, id: &Id) -> Result<Option<VersionedAttachment>> {
        self.repository.transact(|tx| {
            audit(tx, &self.identity)?;
            tx.get(&attachment_key(id))?.map(versioned).transpose()
        })
    }
    /// True means initialization may already have affected the run store, including an unknown result.
    pub fn creation_entered(&mut self, id: &Id) -> Result<bool> {
        self.repository.transact(|tx| {
            audit(tx, &self.identity)?;
            let record = read(tx, id)?;
            creation_entered(tx, &record.value.preparation)
        })
    }
    pub fn prepare(&mut self, request: Preparation) -> Result<VersionedAttachment> {
        validate_preparation(&self.identity, &request)?;
        self.repository.transact(|tx| {
            let mut state = audit(tx, &self.identity)?;
            if let Some(row) = tx.get(&attachment_key(&request.id))? {
                let old = versioned(row)?;
                if !same(&old.value.preparation, &request)? {
                    return Err(StoreError::KeyConflict);
                }
                return Ok(old);
            }
            if tx.get(&run_key(&request.scope.run))?.is_some() {
                return Err(StoreError::KeyConflict);
            }
            if state.current.is_some() {
                return invalid("another run attachment is still Preparing or Attached");
            }
            if state.count.0 >= MAX_ATTACHMENTS as u64 {
                return invalid("attachment history capacity reached");
            }
            for row in tx.scan(PREFIX)? {
                let old: Attachment = decode(&row, RECORD)?;
                if old.preparation.run_journal == request.run_journal {
                    return Err(StoreError::KeyConflict);
                }
            }
            let value = Attachment {
                preparation: request.clone(),
                phase: Phase::Preparing,
                completion: None,
            };
            let row = tx.put(&attachment_key(&request.id), None, &doc(RECORD, &value)?)?;
            tx.put(
                &run_key(&request.scope.run),
                None,
                &doc(INDEX, &request.id)?,
            )?;
            state.current = Some(request.id.clone());
            state.count = Counter(state.count.0 + 1);
            save_state(tx, &state)?;
            event(tx, &value)?;
            versioned(row)
        })
    }

    /// Only a verified, exactly bound run store can complete Preparing -> Attached.
    /// Returns the existing request Journal only after the attachment commit succeeds.
    pub fn attach<Q: Repository>(
        &mut self,
        mut run: RunStore<Q>,
    ) -> Result<(VersionedAttachment, Journal<Q>)> {
        run.verify()?;
        let binding = run.binding.clone();
        let attached = self.repository.transact(|tx| {
            let state = audit(tx, &self.identity)?;
            let mut record = read(tx, &binding.preparation.id)?;
            run_store::matches(&self.identity, &record.value.preparation, &binding)?;
            if !creation_entered(tx, &record.value.preparation)? {
                return integrity("run creation entry missing before attachment");
            }
            if record.value.phase == Phase::Closed
                || state.current.as_ref() != Some(&binding.preparation.id)
            {
                return invalid("closed or inactive attachment cannot attach");
            }
            if record.value.phase == Phase::Attached {
                return Ok(record);
            }
            record.value.phase = Phase::Attached;
            let row = tx.put(
                &attachment_key(&binding.preparation.id),
                Some(record.revision),
                &doc(RECORD, &record.value)?,
            )?;
            event(tx, &record.value)?;
            versioned(row)
        })?;
        let journal = Journal::open(run.repository, binding.preparation.scope)?;
        Ok((attached, journal))
    }

    /// Records normal completion only. Caller must first validate P authenticity/freshness
    /// and planner retirement; neither a stored view nor Closed is a native safety receipt.
    pub fn close_completed<Q: Repository>(
        &mut self,
        run: &mut RunStore<Q>,
        completion: production::View,
    ) -> Result<VersionedAttachment> {
        run.verify()?;
        let binding = &run.binding;
        validate_completion(&self.identity, &binding.preparation, &completion)?;
        self.repository.transact(|tx| {
            let mut state = audit(tx, &self.identity)?;
            let mut record = read(tx, &binding.preparation.id)?;
            run_store::matches(&self.identity, &record.value.preparation, binding)?;
            if let Some(saved) = &record.value.completion {
                return if same(saved.as_ref(), &completion)? {
                    Ok(record)
                } else {
                    Err(StoreError::KeyConflict)
                };
            }
            if record.value.phase != Phase::Attached
                || state.current.as_ref() != Some(&binding.preparation.id)
            {
                return invalid("only the attached run can close");
            }
            record.value.phase = Phase::Closed;
            record.value.completion = Some(Box::new(completion));
            let row = tx.put(
                &attachment_key(&binding.preparation.id),
                Some(record.revision),
                &doc(RECORD, &record.value)?,
            )?;
            state.current = None;
            save_state(tx, &state)?;
            event(tx, &record.value)?;
            versioned(row)
        })
    }
}

fn audit(tx: &mut dyn Transaction, expected: &Identity) -> Result<State> {
    let header = required(tx, &name("attachment/header"))?;
    if header.revision != Counter(1) || decode::<Identity>(&header, HEADER)? != *expected {
        return integrity("attachment service header changed");
    }
    let state: State = decode(&required(tx, &name("attachment/state"))?, STATE)?;
    let rows = tx.scan(PREFIX)?;
    let indices = tx.scan("attachment/by-run/")?;
    let creations = tx.scan(CREATION_PREFIX)?;
    if rows.len() > MAX_ATTACHMENTS
        || rows.len() as u64 != state.count.0
        || indices.len() != rows.len()
    {
        return integrity("attachment history/index count differs");
    }
    let mut active = Vec::new();
    let mut journals = BTreeSet::new();
    let mut creation_count = 0;
    for row in rows {
        let entry: Attachment = decode(&row, RECORD)?;
        validate_preparation(expected, &entry.preparation)?;
        if row.key != attachment_key(&entry.preparation.id)
            || !journals.insert(entry.preparation.run_journal.clone())
        {
            return integrity("attachment identity/index differs");
        }
        let index = required(tx, &run_key(&entry.preparation.scope.run))?;
        if index.revision != Counter(1) || decode::<Id>(&index, INDEX)? != entry.preparation.id {
            return integrity("run attachment index changed");
        }
        let revision = match entry.phase {
            Phase::Preparing => 1,
            Phase::Attached => 2,
            Phase::Closed => 3,
        };
        if row.revision != Counter(revision)
            || (entry.phase == Phase::Closed) != entry.completion.is_some()
        {
            return integrity("attachment phase/completion/revision differs");
        }
        if creation_entered(tx, &entry.preparation)? {
            creation_count += 1;
        } else if entry.phase != Phase::Preparing {
            return integrity("attached run creation entry missing");
        }
        if let Some(completion) = &entry.completion {
            validate_completion(expected, &entry.preparation, completion)?;
        } else {
            active.push(entry.preparation.id);
        }
    }
    if creation_count != creations.len() {
        return integrity("orphan run creation entry");
    }
    if active.len() > 1 || active.first() != state.current.as_ref() {
        return integrity("attachment current pointer differs");
    }
    Ok(state)
}
fn validate_preparation(identity: &Identity, p: &Preparation) -> Result<()> {
    if !identity.scope.matches(&p.scope)
        || p.epoch.0 == 0
        || p.basis.sequence.0 == 0
        || p.basis.run_revision.0 == 0
        || p.basis.cell_revision.0 == 0
        || p.basis.checked_at.clock_id.is_empty()
        || p.basis.checked_at.clock_id.len() > 256
    {
        return invalid("attachment preparation scope/basis differs");
    }
    Ok(())
}
fn validate_completion(identity: &Identity, p: &Preparation, v: &production::View) -> Result<()> {
    production::validate(v).map_err(StoreError::Invalid)?;
    if v.installation != identity.scope.installation
        || v.store_generation != identity.scope.store_generation
        || v.definition.sha256 != p.scope.definition
        || v.resolved.sha256 != p.scope.resolved_digest
        || v.run.run.id != p.scope.run
        || v.run.run.cell != p.scope.cell
        || v.run.run.state != RunState::Completed
        || v.run.run.executor_session.as_ref() != Some(&p.executor_session)
        || v.run.revision < p.basis.run_revision
        || (v.runtime_boot == p.basis.runtime_boot && v.sequence < p.basis.sequence)
    {
        return invalid("only exact completed run evidence can close an attachment");
    }
    Ok(())
}
fn read(tx: &mut dyn Transaction, id: &Id) -> Result<VersionedAttachment> {
    versioned(required(tx, &attachment_key(id))?)
}
fn versioned(row: Record) -> Result<VersionedAttachment> {
    Ok(VersionedAttachment {
        revision: row.revision,
        value: decode(&row, RECORD)?,
    })
}
fn save_state(tx: &mut dyn Transaction, state: &State) -> Result<()> {
    let row = required(tx, &name("attachment/state"))?;
    tx.put(&row.key, Some(row.revision), &doc(STATE, state)?)?;
    Ok(())
}
fn required(tx: &mut dyn Transaction, key: &Name) -> Result<Record> {
    tx.get(key)?
        .ok_or_else(|| StoreError::Integrity(format!("required record missing: {key}")))
}
fn attachment_key(id: &Id) -> Name {
    name(&format!("{PREFIX}{id}"))
}
fn run_key(run: &Id) -> Name {
    name(&format!("attachment/by-run/{run}"))
}
fn creation_key(id: &Id) -> Name {
    name(&format!("{CREATION_PREFIX}{id}"))
}
fn creation_entered(tx: &mut dyn Transaction, preparation: &Preparation) -> Result<bool> {
    let Some(row) = tx.get(&creation_key(&preparation.id))? else {
        return Ok(false);
    };
    if row.revision != Counter(1) || !same(&decode::<Preparation>(&row, CREATION)?, preparation)? {
        return integrity("run creation entry identity changed");
    }
    Ok(true)
}
fn name(value: &str) -> Name {
    Name::new(value).expect("fixed prefix and validated UUID")
}
fn doc<T: Serialize>(schema: &str, value: &T) -> Result<Document> {
    let bytes = canonical::bytes(value).map_err(|e| StoreError::Invalid(e.to_string()))?;
    Ok(Document {
        schema: name(schema),
        value: canonical::decode_json(&bytes).map_err(|e| StoreError::Invalid(e.to_string()))?,
    })
}
fn decode<T: DeserializeOwned>(record: &Record, schema: &str) -> Result<T> {
    if record.document.schema.as_str() != schema {
        return integrity("attachment record schema differs");
    }
    canonical::decode_json(
        &canonical::bytes(&record.document.value)
            .map_err(|e| StoreError::Integrity(e.to_string()))?,
    )
    .map_err(|e| StoreError::Integrity(e.to_string()))
}
fn same<T: Serialize>(a: &T, b: &T) -> Result<bool> {
    Ok(
        canonical::bytes(a).map_err(|e| StoreError::Invalid(e.to_string()))?
            == canonical::bytes(b).map_err(|e| StoreError::Invalid(e.to_string()))?,
    )
}
fn event(tx: &mut dyn Transaction, value: &Attachment) -> Result<()> {
    let id = Id::new(uuid::Uuid::new_v4().to_string()).expect("UUID");
    tx.append(&id, &doc("rx.executor-attachment-transition.v1", value)?)?;
    Ok(())
}
fn invalid<T>(message: &str) -> Result<T> {
    Err(StoreError::Invalid(message.into()))
}
fn integrity<T>(message: &str) -> Result<T> {
    Err(StoreError::Integrity(message.into()))
}
