import json,os,subprocess,uuid
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
out=Path(os.environ['RX_PACKAGE_EVIDENCE']);fixture=Path(os.environ['RX_BROWSER_PACKAGE_FIXTURE']);info=json.loads((fixture/'fixture.json').read_text());platform=Path(os.environ['RX_PLATFORM_REPO']);tool=os.environ['RX_PROCESS_PACKAGE_BIN'];origin='http://127.0.0.1:5173';headers={'Origin':origin,'Content-Type':'application/json','X-RX-Client':'browser-v1'}

def sign(report):
 env=dict(os.environ,RX_BROWSER_REVIEW_REPORT=str(report));subprocess.run([str(platform/'tools/cargo'),'test','-p','rx-api','--test','http','sign_operator_review_fixture','--locked','--','--ignored','--exact'],cwd=platform,env=env,check=True,capture_output=True)
def login(page,user):
 page.get_by_label('Account',exact=True).fill(user);page.get_by_label('Password',exact=True).fill('browser-fixture-password');page.get_by_role('button',name='Sign in',exact=True).click();expect(page.get_by_role('button',name='Sign out',exact=True)).to_be_visible();page.get_by_role('button',name='Package review',exact=True).click();expect(page.get_by_role('heading',name='Review packages and record decisions')).to_be_visible()
with sync_playwright() as p:
 browser=p.chromium.launch(headless=True);context=browser.new_context(viewport={'width':1440,'height':1100});page=context.new_page();errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 page.goto(origin);page.wait_for_load_state('networkidle');page.screenshot(path=str(out/'initial.png'),full_page=True)
 # Reuse the actual app's accessible labels; adapt only after inspecting rendered DOM if needed.
 (out/'initial-dom.html').write_text(page.content())
 login(page,'admin')
 page.locator('summary').filter(has_text='Import signed package').click();page.get_by_label('Intake title',exact=True).fill('Laser material supply review');page.get_by_label('Relative path in intake directory',exact=True).fill('package');page.get_by_label('Package content identifier',exact=True).fill(info['object']['manifest']);page.get_by_label('Package signature identifier',exact=True).fill(info['object']['signature']);page.get_by_role('button',name='Request package intake',exact=True).click()
 expect(page.locator('.package-item').filter(has_text='Laser material supply review')).to_be_visible();expect(page.get_by_role('heading',name='Laser material supply review',exact=True)).to_be_visible()
 page.locator('summary').filter(has_text='Create new review request').click();page.get_by_label('load Operation bindings',exact=True).select_option(index=1);page.get_by_role('button',name='Create review request',exact=True).click();expect(page.get_by_role('button',name='Export verification request')).to_be_visible()
 with page.expect_download() as download:page.get_by_role('button',name='Export verification request').click()
 request_path=out/'review-request.json';download.value.save_as(str(request_path));request=json.loads(request_path.read_text());review=request['id'];intake=request['intake']
 report_dir=Path(info['exchange'])/'report';result=subprocess.run([tool,'review',str(Path(info['exchange'])/'package'),info['policy'],str(request_path),str(report_dir)],check=True,capture_output=True,text=True);assert json.loads(result.stdout)['compiler_checks_passed'];sign(report_dir/'verification.json');report_digest=json.loads(result.stdout)['report_digest']
 page.locator('summary').filter(has_text='Register signed verification evidence').click();page.get_by_label('Verification evidence relative path',exact=True).fill('report');page.get_by_label('Verification report identifier',exact=True).fill(report_digest);page.get_by_role('button',name='Request verification evidence registration').click();expect(page.get_by_text('Software review evidence ready',exact=True)).to_be_visible();expect(page.get_by_role('button',name='Approve software review',exact=True)).to_be_disabled()
 page.screenshot(path=str(out/'author-cannot-approve.png'),full_page=True)
 page.get_by_role('button',name='Sign out',exact=True).click();login(page,'reviewer');page.locator('.package-item').filter(has_text='Laser material supply review').click();page.locator('.review-list button').first.click();expect(page.get_by_text('Software review evidence ready',exact=True)).to_be_visible()
 page.get_by_label('Review note',exact=True).fill('I reviewed the source, compiled result, and cell operations.');page.get_by_role('checkbox',name='I have reviewed the source, compiled result, cell bindings, and this review version.').check()
 # A new report version under the same signed report invalidates the displayed acknowledgement.
 response=context.request.post(origin+'/api/v1/process-review/reports',headers=headers,data={'request_key':str(uuid.uuid4()),'command':{'review':review,'cell':'cell/demo','expected':'1','directory':'report','report_digest':report_digest}});assert response.ok,response.text()
 expect(page.get_by_role('heading',name='Verification evidence r2',exact=True)).to_be_visible();expect(page.get_by_role('checkbox')).not_to_be_checked();expect(page.get_by_role('button',name='Approve software review',exact=True)).to_be_disabled()
 page.get_by_label('Verification version to view',exact=True).fill('1');page.get_by_role('button',name='View historical version',exact=True).click();expect(page.get_by_text('Historical review · read only',exact=True)).to_be_visible();expect(page.get_by_role('button',name='Approve software review',exact=True)).to_be_disabled();page.get_by_role('button',name='View latest review',exact=True).click();expect(page.get_by_role('heading',name='Verification evidence r2',exact=True)).to_be_visible()
 page.get_by_role('checkbox').check();page.get_by_role('button',name='Approve software review',exact=True).click();expect(page.locator('dialog[open]')).to_be_visible()
 response=context.request.post(origin+'/api/v1/process-review/reports',headers=headers,data={'request_key':str(uuid.uuid4()),'command':{'review':review,'cell':'cell/demo','expected':'2','directory':'report','report_digest':report_digest}});assert response.ok,response.text()
 expect(page.locator('dialog[open]')).not_to_be_visible();expect(page.get_by_role('heading',name='Verification evidence r3',exact=True)).to_be_visible();expect(page.get_by_role('checkbox')).not_to_be_checked()
 page.get_by_role('checkbox').check();page.get_by_role('button',name='Approve software review',exact=True).click();expect(page.locator('dialog[open]')).to_be_visible();page.screenshot(path=str(out/'approval-target.png'))
 lost=[]
 def lose(route):
  lost.append(route.request.post_data_json);response=route.fetch();assert response.ok,response.text();route.abort('failed')
 page.route('**/api/v1/process-review/decisions',lose,times=1);page.get_by_role('button',name='Record approval for this version',exact=True).click();expect(page.get_by_text('The request outcome needs verification',exact=True)).to_be_visible();expect(page.get_by_role('button',name='Check original request',exact=True)).to_be_enabled();assert context.request.get(origin+f'/api/v1/process-review?cell=cell%2Fdemo&id={review}').json()['decision']['revision']=='1'
 page.reload();page.wait_for_load_state('networkidle');received=[]
 def retry(route):received.append(route.request.post_data_json);route.continue_()
 page.route('**/api/v1/process-review/decisions',retry,times=1);page.get_by_role('button',name='Check original request',exact=True).click();expect(page.get_by_text('The request outcome needs verification',exact=True)).not_to_be_visible();assert received==lost
 page.get_by_role('button',name='Package review',exact=True).click();page.locator('.package-item').filter(has_text='Laser material supply review').click();page.locator('.review-list button').first.click();expect(page.get_by_text('Software approval is recorded for this version',exact=True)).to_be_visible();page.screenshot(path=str(out/'approved-software-review.png'),full_page=True)
 page.set_viewport_size({'width':390,'height':844});page.screenshot(path=str(out/'review-mobile.png'),full_page=True);assert page.evaluate('document.documentElement.scrollWidth <= innerWidth'),'mobile overflow'
 view=context.request.get(origin+f'/api/v1/process-review?cell=cell%2Fdemo&id={review}').json();assert not view['activation_authorized'] and view['approval_matches_current_review'];assert view['decision']['revision']=='1';assert not context.request.get(origin+'/api/v1/overview').json()['cells'][0]['runs'];assert not errors,errors
 (out/'result.json').write_text(json.dumps({'status':'PASS','review':review,'intake':intake,'real_api':True,'real_s_compiler':True,'test_only_signer':True,'checks':['intake','step binding selection','review request download','signed report submission','self approval denied','new report clears acknowledgement','history is read only','open approval dialog invalidated by new version','explicit target confirmation','lost decision response and same-key recovery after reload','no run or activation','mobile overflow','no JavaScript errors']},indent=2)+'\n');context.close();browser.close()
