file(READ "${RX_PROTO_ROOT}/bundle.json" RX_BUNDLE_JSON)
string(JSON RX_BUNDLE_SCHEMA GET "${RX_BUNDLE_JSON}" schema)
if(NOT RX_BUNDLE_SCHEMA STREQUAL "rx.protocol-source-bundle.v1")
  message(FATAL_ERROR "Unsupported protocol bundle schema")
endif()
string(JSON RX_BUNDLE_COUNT LENGTH "${RX_BUNDLE_JSON}" files)
if(RX_BUNDLE_COUNT LESS 5)
  message(FATAL_ERROR "Incomplete protocol source bundle")
endif()
math(EXPR RX_BUNDLE_LAST "${RX_BUNDLE_COUNT}-1")
foreach(RX_INDEX RANGE 0 ${RX_BUNDLE_LAST})
  string(JSON RX_PATH MEMBER "${RX_BUNDLE_JSON}" files ${RX_INDEX})
  if(IS_ABSOLUTE "${RX_PATH}" OR RX_PATH MATCHES "(^|/)[.][.](/|$)")
    message(FATAL_ERROR "Invalid protocol bundle path")
  endif()
  string(JSON RX_EXPECTED GET "${RX_BUNDLE_JSON}" files "${RX_PATH}")
  file(SHA256 "${RX_PROTO_ROOT}/${RX_PATH}" RX_ACTUAL)
  if(NOT RX_ACTUAL STREQUAL RX_EXPECTED)
    message(FATAL_ERROR "Protocol source digest mismatch: ${RX_PATH}")
  endif()
endforeach()
