const labels: Record<string, string> = {
  SETUP: 'Setup',
  AUTOMATIC: 'Automatic workflow',
  RECOVERY: 'Recovery and intervention',
  NOT_COMMISSIONED: 'Not registered',
  COMMISSIONED: 'Qualification recorded',
  REVALIDATION_REQUIRED: 'Revalidation required',

  PREPARED: 'Prepared',
  EXECUTING: 'Executing',
  PAUSED: 'Paused',
  RECOVERY_REQUIRED: 'Recovery required',
  COMPLETED: 'Attempt completed',
  ABANDONED: 'Abandoned',
  NONE: 'Outcome not determined',
  SUCCEEDED: 'Success confirmed',
  FAILED: 'Failure confirmed',
  CANCELED: 'Cancellation confirmed',
  NOT_EXECUTED: 'Non-execution confirmed',
  UNRESOLVED: 'Unresolved',
  NOT_SENT: 'Not sent',
  MAY_HAVE_EXECUTED: 'May have executed',
  ACCEPTED: 'Acceptance confirmed',
  RUNNING: 'Execution observed',
  ENDED: 'End observed',
  UNKNOWN: 'Unknown',
  VALID: 'No conflict',
  DISPUTED: 'Conflicting evidence',
  HELD: 'Resources held',
  QUARANTINED: 'Quarantined',
  RELEASED: 'Handover confirmed',
  CONFIGURATION_CHANGE: 'Configuration change preparation',
  RUNTIME_RESTART: 'Runtime restart',
  OPERATOR_HOLD: 'Operator hold',
  EXECUTOR_PAUSE: 'Executor pause',
  CASE_DIAGNOSTIC: 'Diagnostic case hold',
  CASE_INTERVENTION: 'Intervention case block',
  PROCEDURE_REPORTED: 'External procedure status reported',
  OUT_OF_SERVICE: 'Out of service · separate revalidation required',
  DIAGNOSTIC_ONLY: 'Diagnostic inquiry',
  PLANNED_ACCESS: 'Planned access',
  FAULT_RECOVERY: 'Fault recovery',
  MAINTENANCE: 'Maintenance',
  CHANGE_REVIEW: 'Change review',
  OPEN: 'Case opened',
  CONTAINMENT_PENDING: 'Awaiting containment confirmation',
  PROCEDURE_ACTIVE: 'External procedure progress recorded',
  REVALIDATING: 'Revalidating',
  READY_FOR_RESTART: 'Restart readiness recorded',
  CLOSED: 'Case closed',
  ESCALATED: 'Support or coordination required',
  AUTHORITY_REVOKED: 'Authority revoked',
  CONDITION_LOST: 'Operating condition lost',
  INTEGRITY_CONFLICT: 'Record conflict',
  DEVICE_RESTART: 'Device restart',
  OBSERVER: 'Read access',
  OPERATOR: 'Operations',
  RECOVERY_LEAD: 'Recovery lead',
  ENGINEER: 'Engineering',
  VERIFIER: 'Verification',
  RELEASE_MANAGER: 'Release management',
  ACCOUNT_ADMIN: 'Account administration',
  EXECUTOR: 'Workflow executor',
  HOST: 'Device connection',
  OPERATOR_API: 'Operator API service',
};
export const text = (s: string) => labels[s] ?? s;
export const count = (value: number | string, singular: string, plural = `${singular}s`) =>
  `${value} ${String(value) === '1' ? singular : plural}`;
export const short = (s: string) => s.slice(0, 8);
export const time = (n: number) =>
  new Intl.DateTimeFormat('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  }).format(n);
