const labels: Record<string, string> = {
  SETUP: '셋업',
  AUTOMATIC: '자동 공정',
  RECOVERY: '복구·개입',
  NOT_COMMISSIONED: '미등록',
  COMMISSIONED: '자격 기록 있음',
  REVALIDATION_REQUIRED: '재검증 필요',

  PREPARED: '시작 전',
  EXECUTING: '실행 중',
  PAUSED: '일시 정지',
  RECOVERY_REQUIRED: '복구 필요',
  COMPLETED: '시도 완료',
  ABANDONED: '종료됨',
  NONE: '결과 미확정',
  SUCCEEDED: '완료 확인',
  FAILED: '실패 확인',
  CANCELED: '취소 확인',
  NOT_EXECUTED: '미실행 확인',
  UNRESOLVED: '해결되지 않음',
  NOT_SENT: '전달 전',
  MAY_HAVE_EXECUTED: '실행 가능성 있음',
  ACCEPTED: '접수 확인',
  RUNNING: '동작 관측',
  ENDED: '종료 관측',
  UNKNOWN: '알 수 없음',
  VALID: '상충 없음',
  DISPUTED: '증거 상충',
  HELD: '자원 보유',
  QUARANTINED: '격리',
  RELEASED: '인계 확인',
  CONFIGURATION_CHANGE: '구성 변경 준비',
  RUNTIME_RESTART: '시스템 재시작',
  OPERATOR_HOLD: '작업자 운전 보류',
  EXECUTOR_PAUSE: '공정 실행기 보류',
  CASE_DIAGNOSTIC: '진단 사건 보류',
  CASE_INTERVENTION: '개입 사건 차단',
  PROCEDURE_REPORTED: '외부 절차 상태 보고',
  OUT_OF_SERVICE: '운전 제외 · 별도 재검증 필요',
  DIAGNOSTIC_ONLY: '진단 조회',
  PLANNED_ACCESS: '계획된 접근',
  FAULT_RECOVERY: '이상 복구',
  MAINTENANCE: '정비',
  CHANGE_REVIEW: '변경 검토',
  OPEN: '사건 접수',
  CONTAINMENT_PENDING: '조치·격리 확인 대기',
  PROCEDURE_ACTIVE: '외부 절차 진행 기록',
  REVALIDATING: '재검토 중',
  READY_FOR_RESTART: '재시작 준비 기록',
  CLOSED: '사건 종료',
  ESCALATED: '지원·조정 필요',
  AUTHORITY_REVOKED: '권한 회수',
  CONDITION_LOST: '운전 조건 상실',
  INTEGRITY_CONFLICT: '기록 상충',
  DEVICE_RESTART: '장비 재시작',
  OBSERVER: '조회',
  OPERATOR: '운영',
  RECOVERY_LEAD: '복구 담당',
  ENGINEER: '구성 설계',
  VERIFIER: '검증',
  RELEASE_MANAGER: '배포',
  ACCOUNT_ADMIN: '계정 관리',
  EXECUTOR: '공정 실행기',
  HOST: '장비 연결',
  OPERATOR_API: '운영 API 서비스',
};
export const text = (s: string) => labels[s] ?? s;
export const short = (s: string) => s.slice(0, 8);
export const time = (n: number) =>
  new Intl.DateTimeFormat('ko-KR', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  }).format(n);
